image: Visual Studio 2017
configuration: Release
build_script:
- ps: >-
    cd C:/tools/vcpkg

    git pull

    ./bootstrap-vcpkg.bat

    vcpkg install sfml --head 
    
    vcpkg install enet

    cd C:/projects/

    # Build/Install tmxlite, which the demo requires

    git clone https://github.com/fallahn/tmxlite

    cd tmxlite/tmxlite; mkdir build; cd build

    cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=C:/tools/vcpkg/installed -DCMAKE_BUILD_TYPE=Release

    cmake --build . --target install --config Release

    cd ../../../xygine

    # Build xygine libs first

    mkdir build; cd build

    cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=C:/tools/vcpkg/installed -DBUILD_DEMO=ON

    cmake --build . --target install

    cmake --build . --target package

artifacts:
  - path: 'build/*.zip'
    name: xygine
deploy:
  provider: GitHub
  auth_token:
    secure: Uh9bW+VtZC5N7CVz5UpuxZvPJ58SpbsXBvEz6Q4vQhLcjZEFzYMhH+bS9VAPV+S8
  artifact: xygine
  prerelease: true
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only